# Generated by Django 2.1.3 on 2018-11-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='章节名称')),
                ('num', models.IntegerField(verbose_name='章节')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogon', models.CharField(max_length=255, null=True, verbose_name='口号')),
                ('why_learn', models.CharField(max_length=255, null=True, verbose_name='为什么要学这门课')),
            ],
        ),
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='课程名')),
                ('course_img', models.CharField(max_length=32, null=True, verbose_name='课程图片')),
                ('level', models.IntegerField(choices=[(1, '初级'), (2, '中级'), (3, '高级')], default=1, verbose_name='课程等级')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=True, to='luffyCity.UserInfo')),
            ],
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='course',
            field=models.OneToOneField(on_delete=True, to='luffyCity.CourseList'),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='recommend_courses',
            field=models.ManyToManyField(related_name='rc', to='luffyCity.CourseList', verbose_name='推荐课程'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=True, to='luffyCity.CourseList'),
        ),
    ]
